enabled: true
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/custom, user/themes/hotdoy]
org_name: Hotdoy
ficelle: '0'
rythm: 8rem
tracking: '1'
rhythm: 8rem
price_prefix: $
price_suffix: CAD
