title: Hotdoy
default_lang: en
author:
  name: Hotdoy
  email: 
taxonomies:
  - category
metadata:
  description: 'Hotdoy theme for Grav CMS'
summary:
  enabled: true
  format: short
  size: 120
  delimiter: '==='
